#!/bin/bash

# should set toplevel via autoconf?
toplevel=$PWD/../..

# source our common variables and functions
. $toplevel/utils/bootstrap-early/functions


# install linux headers
build_linux_headers()
{
    builddir=.build/kernel
    # get the source tree into our build dir
    rsync -a --exclude .git $packagedir/kernel/ $builddir || exit 1
    pushd $builddir
    make mrproper &&
    make ARCH=$ARCH_TARGET headers_check &&
    make ARCH=$ARCH_TARGET INSTALL_HDR_PATH=dest headers_install || exit 1
    mkdir -p $PREFIX_CROSS/include
    rsync -v dest/include/* $PREFIX_CROSS/include || exit 1
    popd
}



build()
{
    case "$1" in
	linux_headers)
	    build_linux_headers
	    ;;
	ncurses)
	    # probably only need to make the tic program, but this is
	    # easier.  might save us 10M and 1 minute, but it's all
	    # temporary files anyway so we don't really care very much about
	    # the 10M
	    build_generic $1 --prefix=$PREFIX_CROSS --without-debug --without-shared
	    ;;
	gmp)
	    CPPFLAGS=-fexceptions \
		build_generic $1 --prefix=$PREFIX_CROSS --enable-cxx
	    ;;
	mpfr)
	    LDFLAGS="-Wl,-rpath,$PREFIX_CROSS/lib" \
		build_generic $1 --prefix=$PREFIX_CROSS \
		--enable-shared \
		--with-gmp=$PREFIX_CROSS
	    ;;
	mpc)
	    LDFLAGS="-Wl,-rpath,$PREFIX_CROSS/lib" \
		build_generic $1 --prefix=$PREFIX_CROSS \
		--with-gmp=$PREFIX_CROSS \
		--with-mpfr=$PREFIX_CROSS
	    ;;
	ppl)
	    LDFLAGS="-Wl,-rpath,$PREFIX_CROSS/lib" \
		build_generic $1 --prefix=$PREFIX_CROSS \
		--enable-shared \
		--enable-interfaces="c,cxx" \
		--disable-optimization \
		--with-libgmp-prefix=$PREFIX_CROSS \
		--with-libgmpxx-prefix=$PREFIX_CROSS
	    ;;
	cloog-ppl)
	    LDFLAGS="-Wl,-rpath,$PREFIX_CROSS/lib" \
		build_generic $1 --prefix=$PREFIX_CROSS \
		--enable-shared \
		--with-bits=gmp \
		--with-gmp=$PREFIX_CROSS \
		--with-ppl=$PREFIX_CROSS
	    ;;
	binutils)
	    # this was using /tools as apposed to /tools-cross in the CLFS
	    # book
	    AR=ar AS=as setup_generic $1 &&
	    AR=ar AS=as \
		configure_generic $1 --prefix=$PREFIX_CROSS \
		--host=${MACHTYPE_HOST} \
		--target=${MACHTYPE_TARGET} \
		--with-sysroot=${INSTALLROOT} \
		--with-lib-path=/bootstrap/lib \
		--disable-nls \
		--enable-shared \
		--enable-64-bit-bfd || exit 1
	    pushd $builddir || exit 1
	    make configure-host &&
	    make -j3 &&
	    make install || exit 1
	    ;;
	*)
	    build_generic $1 --prefix=$PREFIX_CROSS
	    ;;
    esac
}


packages=""
#packages+=" linux_headers"
#packages+=" file"
#packages+=" ncurses"
#packages+=" gmp"
#packages+=" mpfr"
#packages+=" mpc"
#packages+=" ppl"
#packages+=" cloog-ppl"
packages+=" binutils"
#packages+=" gcc-static"
#packages+=" eglibc-32bit"
#packages+=" eglibc-64bit"
#packages+=" gcc"

for p in $packages; do
    echo "building cross package: $p"
    build $p || exit 1
done
