#!/bin/bash

# should set toplevel via autoconf?
toplevel=$PWD/../..

# source our common variables and functions
. $toplevel/utils/bootstrap-early/functions


# install linux headers
build_linux_headers()
{
    builddir=.build/kernel
    # get the source tree into our build dir
    rsync -a --exclude .git $packagedir/kernel/ $builddir || exit 1
    pushd $builddir
    make mrproper &&
    make ARCH=$ARCH_TARGET headers_check &&
    make ARCH=$ARCH_TARGET INSTALL_HDR_PATH=dest headers_install || exit 1
    mkdir -p $PREFIX_CROSS/include
    rsync -v dest/include/* $PREFIX_CROSS/include || exit 1
    popd
}



build()
{
    case "$1" in
	linux_headers)
	    build_linux_headers
	    ;;
	ncurses)
	    # probably only need to make the tic program, but this is
	    # easier.  might save us 10M and 1 minute, but it's all
	    # temporary files anyway so we don't really care very much about
	    # the 10M
	    build_generic $1 --prefix=$PREFIX_CROSS --without-debug --without-shared
	    ;;
	*)
	    build_generic $1 --prefix=$PREFIX_CROSS
	    ;;
    esac
}


packages="linux_headers file ncurses"

for p in $packages; do
    echo "building cross package: $p"
    build $p || exit 1
done
