#!/bin/sh

exec < /dev/console > /dev/console 2>&1

# mount tmpfs for /dev
#
# FIXME: -n?
mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev

# create initial device nodes
mknod /dev/console c 5 1
mknod /dev/null c 1 3
mknod /dev/kmsg c 1 11
mkdir /dev/pts
mkdir -m 1777 /dev/shm
ln -fs /proc/self/fd /dev/fd
ln -fs fd/0 /dev/stdin
ln -fs fd/1 /dev/stdout
ln -fs fd/2 /dev/stderr

# too bad busybox's shell doesn't do this...
#
# FIXME: uh, how about 'for x in [0-6]'?
#
#for x in {0,1,2,3,4,5,6}; do
#    mknod -m 600 /dev/tty$x c 4 $x
#done
mknod -m 600 /dev/tty0 c 4 0
mknod -m 600 /dev/tty1 c 4 1
mknod -m 600 /dev/tty2 c 4 2
mknod -m 600 /dev/tty3 c 4 3
mknod -m 600 /dev/tty4 c 4 4
mknod -m 600 /dev/tty5 c 4 5
mknod -m 600 /dev/tty6 c 4 6

# mount virtual filesystems
#
# FIXME: -n?
#
# FIXME: should we control mounting o these via fstab or not?  we're
#        inconsistent right now...
mount -t devpts devpts /dev/pts
mount -t proc proc /proc
mount -t sysfs sysfs /sys

# create /etc/mtab symlink
#ln -fs /proc/mounts /etc/mtab

# setup hotplug
echo /sbin/mdev > /proc/sys/kernel/hotplug

# FIXME: this is segfaulting on 32bit systems? looks like it works fine on
#        x86_64...
#
mdev -s

# mount everything else in fstab
mount -a
