#!/bin/bash

# which packages need to be built should be determined by configure script

# should set toplevel via autoconf?
toplevel=$PWD/../..

# source our common variables and functions
. $toplevel/utils/bootstrap-early/functions


pacakges=""

# add rsync so we can use it to copy source trees for packages that don't
# support out-of-tree builds
packages+=" rsync"

# to ensure that we don't inadvertantly use a modified version with
# non-standard extensions to build our filesystems
packages+=" e2fsprogs"

# might also want to make sure that the host system has a usable ncurses
# (and ncurses-devel) library.  otherwise we can't run the 'menuconfig'
# target for kernel and busybox configuration
packages+=" ncurses"

# help2man is needed to build man pages for texinfo after running autoreconf
packages+=" help2man"

# install these to make sure the rest of the build is done using the GNU
# build tools we test against
packages+=" make"
packages+=" m4"
packages+=" autoconf"
packages+=" automake"
packages+=" libtool"
packages+=" pkg-config"
packages+=" bison"
packages+=" gettext"
packages+=" gperf"


build()
{
    case "$1" in
	ncurses)
	    build_generic $1 --prefix=$PREFIX_EARLY --with-shared || exit 1
	    ;;
	help2man)
	    build_generic $1 --prefix=$PREFIX_EARLY --disable-nls || exit 1
	    ;;
	*)
	    autoreconf=yes build_generic $1 --prefix=$PREFIX_EARLY || exit 1
    esac
}

# FIXME: add code here to configure sudo. for now, I've set up my host
#        system to give my user unlimited unpassword root access...


# create a /bootstrap symlink on the host system pointing to $BABY/bootstrap
# so that we don't have to go crazy sorting out chroot vs non-chroot paths
# throughout.  this would probably involve having to sort out 2 sets of
# patches for each affected package, so requiring root priveledges for just
# this one thing seems like an ok compromise.
#
# FIXME: should reevaluate this later.  if sorting out /bootstrap vs
#        $BABY/bootstrap turns out to be easy, we should take this out.
mkdir -p $BABY$PREFIX_FINAL || exit 1
if [ "`readlink $PREFIX_FINAL 2>/dev/null`" != "$BABY$PREFIX_FINAL" ]; then
    echo "need root priveledges to create $PREFIX_FINAL symlink"
    sudo ln -s $BABY$PREFIX_FINAL $PREFIX_FINAL || exit 1
fi
mkdir -p $BABY$PREFIX_CROSS || exit 1
if [ "`readlink $PREFIX_CROSS 2>/dev/null`" != "$BABY$PREFIX_CROSS" ]; then
    echo "need root priveledges to create $PREFIX_CROSS symlink"
    sudo ln -s $BABY$PREFIX_CROSS $PREFIX_CROSS || exit 1
fi

# build and install each package in our /ruckus/staging tree
for p in $packages; do
    echo "building package: $p"
    build $p || exit 1
done
