#!/bin/bash

# FIXME: make stage2 builddir configurable somehow?
#
export ruckus_srcdir=/ruckus
export ruckus_builddir=/ruckus-build

# source our common variables and functions
. $ruckus_srcdir/utils/bootstrap-early/functions

# check for the control file
if [ ! -f $RUCKUS_BOOTSTRAP_STAGE2_FILE ]; then
    exec login
fi

echo "running source ruckus bootstrap-stage2..."

# lookup ownership of /ruckus to determine build user/group
build_uid=`stat -c %u $ruckus_srcdir`
build_gid=`stat -c %g $ruckus_srcdir`

# FIXME: adding group and user on the build system will result in those being
#        captured by dumped images... we'll want to remove these either prior
#        to dumping or after resoring in the installer.

# add group if needed
build_group=$(awk -F: "/:$build_gid:/ {print \$1}" /etc/group)
if [ -z "$build_group" ]; then
    build_group=ruckus
    echo "adding group '$build_group' with gid $build_gid"
    addgroup -g $build_gid $build_group
fi

# add user if needed
#
# FIXME: should really use ^ to search from beggining of line, but it doesn't
#        look like busybox's awk supports this.
#
build_user=$(awk -F: "/$build_uid:/ {print \$1}" /etc/passwd)
if [ -z "$build_user" ]; then
    build_user=ruckus
    echo "adding user '$build_user' with uid $build_uid"
    adduser -h $ruckus_builddir -G $build_group -D -H -u $build_uid $build_user
    passwd -d $build_user
    cp /root/.profile $ruckus_builddir/
    chown $build_user:$build_group $ruckus_builddir/.profile
    chmod 664 $ruckus_builddir/.profile
fi

# kick off the builder as build_user
#
# NOTE: build_user will have to use sudo to do it's installations.
#
# NOTE: The '-' is indeed quite intentional.  It forces parsing of
#       build_user's .profile, which is where we've already set a whole
#       bunch of important variables.
su - $build_user -c "$ruckus_srcdir/utils/bootstrap-stage2/go"

# NOTE: we intentionally don't check for failure here.  if we don't rm this
#       file, init will start this script right back up again... looping
#       infinitely.  if there was an error during the build, the user is
#       going to have to handle kicking us back off.
rm -f $RUCKUS_BOOTSTRAP_STAGE2_FILE
