#!/bin/bash

# These variables get set by the Makefile, but try to autodetect them assuming
# we're building in-tree by hand if they're not set
[ -n "$ruckus_srcdir" ] || ruckus_srcdir=$PWD/../..
[ -n "$ruckus_builddir" ] || ruckus_builddir=$PWD/../..

# source our common variables and functions
. $ruckus_srcdir/utils/bootstrap-early/functions

# we've got bootstrap-stage1-specific config files in here
ruckus_confdir=$ruckus_srcdir/utils/bootstrap-stage1/config


build()
{
    # FIXME: CLFS book says CFLAGS and CXXFLAGS NEED to be unset
    #        during cross stage, but it writes the unset commands into
    #        .bashrc, which is still in use in later stages prior to
    #        booting/chrooting into the baby system...  Do we need to
    #        unset them here?
    unset CFLAGS
    unset CXXFLAGS
    unset CPPFLAGS
    unset LDFLAGS

    # set some common variables for all targets
    #
    # NOTE: We don't need any conditionals here because all supported build
    #       types use CLFS_TARGET for --host throughout the stage1 bootstrap.
    OPTS="--prefix=$PREFIX_TOOLS"
    OPTS+=" --build=${CLFS_HOST}"
    OPTS+=" --host=${CLFS_TARGET}"

    # put libs in lib64 if we're building x86_64 multilib
    if [ -n "$BUILD32" ]; then
	OPTS+=" --libdir=$PREFIX_TOOLS/lib64"
    fi

    OPTS+=" --disable-static"
    OPTS+=" --enable-shared"
    OPTS+=" --disable-nls"

    set_cross_compile

    case "$1" in
	gmp)
	    CC_FOR_BUILD=gcc \
		build_generic $1 $OPTS \
		--enable-cxx || exit 1
	    ;;

        cloog)
            setup_generic $1 &&
	    configure_generic $1 $OPTS \
		--with-isl=system || exit 1

            # prevent the attempted installation of an invalid file
            pushd $builddir &&
            sed -i '/cmake/d' Makefile &&
            popd || exit 1

            compile_generic $1 || exit 1
            ;;

	zlib)
	    # NOTE: zlib doesn't use autotools... despite the "configure"
	    #       script and autotool-ish configure flags.  This means it
	    #       doesn't support out-of-tree builds, and its build system
	    #       usage is just different enough to break our
	    #       configure_generic routine...
	    #
	    # FIXME: i think zlib is using CMake, which we should
	    #        perhaps build support for into our generic build
	    #        scripts... although, the real problem here is
	    #        configure failing if passed any invalid args...
	    build_in_tree=yes setup_generic $1 || exit 1

	    # NOTE: It also fails to configure if any unknown flags are passed
	    #       in, so we can't use our generic OPTS variable...
	    OPTS="--prefix=$PREFIX_TOOLS"

	    if [ -n "$BUILD32" ]; then
		OPTS+=" --libdir=$PREFIX_TOOLS/lib64"
	    fi

	    pushd $builddir &&
	    ./configure $OPTS &&
	    popd || exit 1

	    compile_generic $1 || exit 1
	    ;;

	binutils)
	    # FIXME: CLFS 20130924 has a sed statement to fix build problems
	    #        on host systems w/ texinfo 5.x.  My boxes hav 4.x, so I
	    #        don't need it for now, but we should add this check to
	    #        configure.  Either add the sed statement here
	    #        universally and conditionally build texinfo 5.x in
	    #        bootstrap-early or have the configure script enable the
	    #        sed statement only if host system has texinfo 5.x.
	    #        Whichever is easier.
            #
            # FIXME: If we do it, don't forget to un-sed at the end as we might
            #        be building in-tree or referencing a git checkout...
	    #
	    # sed -i -e 's/@colophon/@@colophon/' \
	    #     -e 's/doc@cygnus.com/doc@@cygnus.com/' bfd/doc/bfd.texinfo

            # add 64bit support if desired
            if [ -n "$BUILD64" ]; then
                OPTS+=" --enable-64-bit-bfd"
            fi
            # disable multilib if we're building pure 32 or 64 bit
            if [ -z "$BUILD32" ]; then
                OPTS+=" --disable-multilib"
                OPTS+=" --with-lib-path=$PREFIX_TOOLS/lib"
            else
                OPTS+=" --with-lib-path=$PREFIX_TOOLS/lib64:$PREFIX_TOOLS/lib"
            fi

	    build_generic $1 $OPTS \
                --target=${CLFS_TARGET} || exit 1
	    ;;

	gcc)
	    setup_generic gcc || exit 1

            # apply the CLFS specs patch
	    if [ ! -f $builddir/Makefile ]; then
                # NOTE: gcc has a different patch for pure64 than for x86 or
                #       x86_64 multilib.
                p=$ruckus_srcdir/utils/bootstrap-cross/patches/gcc
                if [ -n "$BUILD64" -a -z "$BUILD32" ]; then
                    p+=/*-pure64_specs-*.patch
                else
                    p+=/*-specs-*.patch
                fi
                echo "applying $p..."
		pushd $source &&
		patch -Np1 < $p || exit 1
		popd
	    fi

	    # make GCC look in PREFIX_TOOLS (i.e., not the host sys)
            #
            # FIXME: This is only ok because we use a dist tarball for gcc's
            #        sources... if we ever swtich to a git tree, we'll need to
            #        either make a copy of the source tree or undo this at the
            #        end...
            pushd $source
	    echo "#undef STANDARD_STARTFILE_PREFIX_1" >> gcc/config/linux.h
            echo "#define STANDARD_STARTFILE_PREFIX_1 \"$PREFIX_TOOLS/lib/\"" >> gcc/config/linux.h
	    echo "#undef STANDARD_STARTFILE_PREFIX_2" >> gcc/config/linux.h
            echo "#define STANDARD_STARTFILE_PREFIX_2 \"\"" >> gcc/config/linux.h
            popd

            # Apply a sed subsitution that will suppress the execution
            # of the fixincludes script:
            #
            # FIXME: same here, we could need to undo this
            pushd $source &&
            cp -v gcc/Makefile.in{,.orig} &&
            sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in &&
            popd || exit 1

	    # NOTE: gcc-static, glibc32, glibc64, and gcc-final should NOT use
	    #       our common OPTS.  these packages are VERY important and so
	    #       we're going to follow the CLFS book exactly.
	    OPTS=""

            # extra tweaks
            if [ -n "$BUILD32" ]; then
                # x86_64 multilib
                OPTS+=" --libdir=$PREFIX_TOOLS/lib64"
            else
                # x86_64 pure or x86
                OPTS+=" --disable-multilib"
            fi

            configure_generic $1 $OPTS --prefix=$PREFIX_TOOLS \
                --build=${CLFS_HOST} --host=${CLFS_TARGET} \
                --target=${CLFS_TARGET} --with-local-prefix=$PREFIX_TOOLS --disable-nls \
                --enable-languages=c,c++ --disable-libstdcxx-pch \
                --with-system-zlib --with-native-system-header-dir=$PREFIX_TOOLS/include \
                --disable-libssp --enable-libstdcxx-time --enable-checking=release || exit 1

	    pushd $builddir || exit 1
	    #  The following will prevent GCC from looking in the wrong
	    #  directories for headers and libraries
            cp -v Makefile{,.orig} &&
            sed "/^HOST_\(GMP\|ISL\|CLOOG\)\(LIBS\|INC\)/s:$PREFIX_TOOLS:$PREFIX_CROSS:g" \
                Makefile.orig > Makefile || exit 1

	    make -j$JOBCOUNT AS_FOR_TARGET="${AS}" LD_FOR_TARGET="${LD}" &&
	    make install &&
	    popd || exit 1

            # Install the libiberty header file that is needed by some packages
            pushd $source &&
            cp -v include/libiberty.h $PREFIX_TOOLS/include &&
            popd || exit 1
	    ;;

	ncurses)
            # FIXME: There is also a CLFS patch to fix some bash-related
            #        problems, but I haven't run into the bug it fixes, so I've
            #        left it out for now.
	    build_generic $1 $OPTS \
                --without-debug --without-ada \
                --enable-overwrite --with-build-cc=gcc || exit 1
	    ;;

	busybox)
	    setup_generic $1 || exit 1

	    # get ready
	    MAKE="make KBUILD_SRC=$source -f $source/Makefile"
	    MAKE+=" ARCH=$CLFS_ARCH CROSS_COMPILE=$CLFS_TARGET-"
	    pushd $builddir &&
	    $MAKE mrproper &&
	    popd || exit 1

	    # create .config
	    #
	    # NOTE: We're planning on using the busybox variants of everything
	    #       possible.  Any exceptions will be noted.
	    #
	    # NOTE: if you want to do a make menuconfig to tweak .config,
	    #       NCURSES_PREFIX has to be set to $PREFIX_TOOLS in order
	    #       to use the ncurses installed via bootstrap-early (and
	    #       our KBUILD patch needs to be applied)
            cp -v $ruckus_confdir/bb-config $builddir/.config &&
	    pushd $builddir &&
	    $MAKE oldconfig &&
            popd || exit 1

	    # build
            pushd $builddir &&
	    $MAKE -j$JOBCOUNT_KBUILD &&
	    popd || exit 1

	    # install
            pushd $builddir &&
	    $MAKE CONFIG_PREFIX=$PREFIX_TOOLS install &&
            popd || exit 1

	    # NOTE: busybox binary is setuid root later on under
	    #       fix-perms

	    # FIXME: there are a bunch of config files in
	    #        $source/examples that we might want installed too
	    #cp $source/examples/depmod.pl $PREFIX_TOOLS/bin &&
	    #chmod 755 $PREFIX_TOOLS/bin/depmod.pl|| exit 1

	    ;;

        bash)
            setup_generic $1 || exit 1

            # fix a bunch of cross-compilation configure errors
            pushd $builddir
            cat > config.cache << "EOF"
ac_cv_func_mmap_fixed_mapped=yes
ac_cv_func_strcoll_works=yes
ac_cv_func_working_mktime=yes
bash_cv_func_sigsetjmp=present
bash_cv_getcwd_malloc=yes
bash_cv_job_control_missing=present
bash_cv_printf_a_format=yes
bash_cv_sys_named_pipes=present
bash_cv_ulimit_maxfds=yes
bash_cv_under_sys_siglist=yes
bash_cv_unusable_rtsigs=no
gt_cv_int_divbyzero_sigfpe=yes
EOF
            popd

	    configure_generic $1 $OPTS \
                --without-bash-malloc --cache-file=config.cache &&
            compile_generic $1 || exit 1
            ;;

        # FIXME: remove?
        bison)
            setup_generic $1 || exit 1

            # Apply a sed which disables the building of bison.help
            # when cross-compiling.
            #
            # NOTE: In $source!  This means we either have to undo
            #       this at the end or make a copy of the source tree
            #       (because bison is a git submodule in src/)
            pushd $source &&
            [ -f Makefile.in.orig ] && exit 1
            cp -v Makefile.in{,.orig} &&
            sed '/bison.help:/s/^/# /' Makefile.in.orig > Makefile.in &&
            popd || exit 1

            # The configure script does not determine the correct
            # value for the following. Set the value manually:
            #
            # NOTE: In $builddir!!!
            pushd $builddir
            echo "ac_cv_prog_lex_is_flex=yes" > config.cache
            popd

            M4=m4 configure_generic $1 $OPTS \
                --cache-file=config.cache &&
            compile_generic $1 || exit 1

            # revert the Makefile.in changes
            pushd $source &&
            mv Makefile.in{.orig,} &&
            popd || exit 1
            ;;

        # FIXME: remove?
	flex)
	    setup_generic $1 || exit 1

	    # When cross-compiling, the configure script does not determine
	    # the correct values for the following, so we'll set the values
	    # manually
	    pushd $builddir &&
	    echo ac_cv_func_malloc_0_nonnull=yes > config.cache &&
	    echo ac_cv_func_realloc_0_nonnull=yes >> config.cache &&
	    popd || exit 1

            M4=m4 configure_generic $1 $OPTS \
		--cache-file=config.cache || exit 1

            # NOTE: We can't let flex build manpage, because help2man tries to
            #       run ../flex --help, which is cross-compiled for a
            #       non-native architecture.  The following sed statements
            #       disable manpage and pdf generation for now.
            #
            # NOTE: CLFS doesn't run into this because they use dist tarballs
            #       as apposed to git trees.
	    #
	    # FIXME: I think?  I'm not entirely sure why the behavior isn't
	    #        more consistent accross host systems... definately
	    #        barfs on avlinux, but even when "cross-compiling" for
	    #        i686 on an i686.  And I swear I got past this w/out any
	    #        issues on a really old 32bit fedora box...
            pushd $builddir &&
            sed -i 's|^dist_man_MANS|#dist_man_MANS|' doc/Makefile &&
            sed -i 's|^dist_doc_DATA|#dist_doc_DATA|' doc/Makefile &&
            popd || exit 1

	    compile_generic $1 || exit 1
	    ;;

	gettext)
            # NOTE: The CLFS 3.0.0 book is getting away with just building
            #       specific binaries inside gettext-tools... I am not so
            #       lucky.  Not sure if it's because I'm building out-of-tree
            #       or if it's the fact that we're building from a git repo
            #       instead of a dist tarball, but my build just turns into a
            #       nightmare unless I just do a plain old full build.
            #
            #       The CLFS book also works around a faulty wcwidth autoconf
            #       check, which I don't seem to need to do.
            #
            #       I do need to disable building the man and texinfo pages,
            #       though...

	    setup_generic $1 || exit

	    # FIXME: We've got --enable-shared --disable-static in
	    #        $OPTS... Does disabling shared now re-enable static?
            #
            # NOTE: We don't need CLFS's config.cache work-around, as mentioned
            #       above.
	    configure_generic $1 $OPTS \
		--disable-shared  || exit 1

            # don't build man in gettext-runtime
            pushd $builddir/gettext-runtime &&
            sed -i 's|\(^SUBDIRS = [[:space:][:alnum:]$(-_]*\) man |\1 |' \
                Makefile &&
            popd || exit 1

            # don't build man or info in gettext-tools
            pushd $builddir/gettext-tools &&
            sed -i 's|\(^SUBDIRS = [[:space:][:alnum:]$(-_]*\) man |\1 |' \
                Makefile &&
            sed -i 's|\(^SUBDIRS =\) doc |\1 |' Makefile &&
            popd || exit 1

            # NOTE: Can't build in parallel (as of 0.19.1)
            #
            JOBCOUNT=1 compile_generic $1 || exit 1
	    ;;

        # FIXME: remove?
	m4)
	    setup_generic $1 || exit 1

	    # Configure can not properly determine the results of the
	    # following tests
	    pushd $builddir &&
	    echo gl_cv_func_btowc_eof=yes > config.cache &&
	    echo gl_cv_func_mbrtowc_incomplete_state=yes >> config.cache &&
	    echo gl_cv_func_mbrtowc_sanitycheck=yes >> config.cache &&
	    echo gl_cv_func_mbrtowc_null_arg=yes >> config.cache &&
	    echo gl_cv_func_mbrtowc_retval=yes >> config.cache &&
	    echo gl_cv_func_mbrtowc_nul_retval=yes >> config.cache &&
	    echo gl_cv_func_wcrtomb_retval=yes >> config.cache &&
	    echo gl_cv_func_wctob_works=yes >> config.cache &&
	    popd || exit 1

	    configure_generic $1 $OPTS \
		--cache-file=config.cache &&
	    compile_generic $1 || exit 1
	    ;;

	texinfo)
            PERL=/usr/bin/perl \
                build_generic $1 $OPTS || exit 1
            ;;

        # FIXME: remove
        texinfo-old)
	    # We have a configure.ac patch and need to force an autoreconf
	    autoreconf=yes \
		setup_generic $1 || exit 1

	    # We need to set LDFLAGS like this so that texinfo's build can
	    # find our bootstrap-early stuff (ncurses, specifically).
	    LDFLAGS=-L$PREFIX_HOSTPREP/lib \
		configure_generic $1 $OPTS || exit 1

	    pushd $builddir &&
	    make -j$JOBCOUNT -C tools/gnulib/lib &&
	    make -j$JOBCOUNT -C tools &&
	    make -j$JOBCOUNT &&
	    make install &&
	    popd || exit 1
	    ;;

	create-dirs)
            mkdir -pv ${CLFS}/{bin,boot,dev,{etc/,}opt,home,lib/firmware,mnt}
            mkdir -pv ${CLFS}/{proc,media/{floppy,cdrom},run/{,shm},sbin,srv,sys}
            mkdir -pv ${CLFS}/var/{lock,log,mail,spool}
            mkdir -pv ${CLFS}/var/{opt,cache,lib/{misc,locate},local}
            install -dv -m 0750 ${CLFS}/root
            install -dv -m 1777 ${CLFS}{/var,}/tmp
            ln -sv ../run ${CLFS}/var/run
            mkdir -pv ${CLFS}/usr/{,local/}{bin,include,lib,sbin,src}
            mkdir -pv ${CLFS}/usr/{,local/}share/{doc,info,locale,man}
            mkdir -pv ${CLFS}/usr/{,local/}share/{misc,terminfo,zoneinfo}
            mkdir -pv ${CLFS}/usr/{,local/}share/man/man{1,2,3,4,5,6,7,8}

	    if [ -n "$BUILD32" ]; then
		# multilib dirs
		mkdir -pv ${CLFS}/lib64
		mkdir -pv ${CLFS}/var/lib64/{misc,locate}
		mkdir -pv ${CLFS}/usr/{,local/}lib64
		install -dv ${CLFS}/usr/lib/locale
		ln -sv ../lib/locale ${CLFS}/usr/lib64
	    fi

	    # I like these too much to leave out...
	    mkdir -pv $CLFS/mnt/{cdrom,flash,floppy,crypt}

	    echo done
	    ;;

	create-symlinks)

            # NOTE: This freshly copy-n-pasted block of symlinks from the CLFS
            #       3.0.0-systemd book differ from what was here previously,
            #       but you can't tell from the patch, because I took out all
            #       the 2>/dev/null redirections and untabified at the same
            #       time:
            #
            #       1. The following symlink were removed:
            #          - /bin/passwd
            #          - /bin/sleep
            #          - /sbin/agetty
            #          - /sbin/blkid
            #          - /var/run (not really, it's made in create-dirs now)
            #
            #       2. The following symlinks have been added:
            #          - /bin/sh
            #          - /sbin/init
            #          - /etc/login.access (broken)
            #          - /etc/login.defs (broken)
            #          - /etc/limits (broken)
            #          - /etc/mtab
            #
            #       3. The stdc++ lib is specified differently (was a glob
            #          before).
            #
            #       4. The sed is new (as is the installation of the libtool
            #          library).

            ln -sv $PREFIX_TOOLS/bin/{bash,cat,echo,grep,login,pwd,stty} ${CLFS}/bin
            ln -sv $PREFIX_TOOLS/bin/file ${CLFS}/usr/bin
            ln -sv $PREFIX_TOOLS/lib/libgcc_s.so{,.1} ${CLFS}/usr/lib
            ln -sv $PREFIX_TOOLS/lib/libstdc++.so{.6,} ${CLFS}/usr/lib
            sed -e "s$PREFIX_TOOLS/usr/" $PREFIX_TOOLS/lib/libstdc++.la > ${CLFS}/usr/lib/libstdc++.la
            ln -sv bash ${CLFS}/bin/sh
            ln -sv $PREFIX_TOOLS/sbin/init ${CLFS}/sbin
            ln -sv $PREFIX_TOOLS/etc/{login.{access,defs},limits} ${CLFS}/etc

            if [ -n "$BUILD32" ]; then
                # x86_64 multilib only
                ln -sv $PREFIX_TOOLS/lib64/libgcc_s.so{,.1} ${CLFS}/usr/lib64
                ln -sv $PREFIX_TOOLS/lib64/libstdc++.so{.6,} ${CLFS}/usr/lib64

            elif [ -n "$BUILD64" ]; then
                # x86_64 pure only

                # To enable some C++ tests in the Glibc and Binutils test
                # suites to link, create a directory and make some symbolic
                # links:
                mkdir -pv ${CLFS}/usr/lib64
                ln -sv $PREFIX_TOOLS/lib/libstdc++.so{.6,} ${CLFS}/usr/lib64
            fi

            # create /etc/mtab symlink for compatibility
            ln -sv /proc/self/mounts ${CLFS}/etc/mtab

            # remove the broken symlinks created by the copy-n-pasted CLFS
            # scriptlet above
            #
            # NOTE: This list can be double-checked with 'find $CLFS -xtype l'
            #
            rm -vf $CLFS/etc/limits
            rm -vf $CLFS/etc/login.{access,defs}

            # We've got some more symlinks to make, because we use our boostrap
            # busybox install in place of a bunch of extra packages that CLFS
            # installs directly in the baby system.  The easiest thing to do
            # here, is just make symlinks to all the busybox symlinks in the
            # baby system by parsing busybox.links in busybox's builddir
            for x in $(cat .build/busybox/busybox.links || exit 1); do
                ln -sv $PREFIX_TOOLS$x $CLFS$x
            done

            echo done
	    ;;

	create-conf)
	    # this will handle config files for init, mdev, users/groups,
            # logfiles, login scripts, fstab, needed device nodes, etc
	    
	    # copy rcS into etc
	    mkdir -vp $CLFS/etc/init.d &&
	    cp -v $ruckus_confdir/rcS $CLFS/etc/init.d || exit 1

            # install mdev config
            #
            # NOTE: We need replace uucp with tty in here for ttyS* because we
            #       haven't created a uucp user/group (yet?).
            #
            # FIXME: Should we just go ahead and make a uucp user account by
            #        default?  CLFS doesn't, but that doesn't mean I can't...
            #        Does busybox provide cu or any other tools from the uucp
            #        package?
            #
            cp -v $ruckus_srcdir/src/busybox/examples/mdev_fat.conf \
                $CLFS/etc/mdev.conf &&
            sed -i 's|uucp|tty|' $CLFS/etc/mdev.conf &&
            cp -v $ruckus_srcdir/src/busybox/examples/mdev.conf.* \
                $CLFS/etc/ || exit 1

	    # copy passwd and group files into etc
	    cp -v $ruckus_confdir/{passwd,group} $CLFS/etc || exit 1
	    
	    # initialize login related log files.
	    #
	    # NOTE: busybox's init replacement might not use these, but if
	    #       switch over to the real sysvinit later on we'll want
	    #       these files
            #
            # FIXME: dup! check go2
	    #touch ${CLFS}/var/run/utmp ${CLFS}/var/log/{btmp,lastlog,wtmp} &&
	    #chmod -v 664 ${CLFS}/var/run/utmp ${CLFS}/var/log/lastlog &&
	    #chmod -v 600 ${CLFS}/var/log/btmp || exit 1

	    # copy profile into root's homedir
	    cp -v $ruckus_confdir/profile $CLFS/root/.profile

	    # make sure these build variables are set
            #
            # NOTE: The CLFS_HOST and CLFS_TARGET variables are no longer
            #       needed at this point.  The CLFS book does not put them in
            #       .profile and neither do we.
            #
            # NOTE: The BUILD32 and BUILD64 CLFS variables are used throughout
            #       the final system build.
            #
            # NOTE: The CLFS_TARGET32 variable is still needed when we go to
	    #       build some 32bit libs at the beginning of the final system
	    #       build (looks like cloog is the last one that needs it).
            #
            # FIXME: Why does nothing after cloog need --host=$CLFS_TARGET32
            #        when building 32bit libs...?
	    echo export BUILD32=\"$BUILD32\" >> $CLFS/root/.profile
	    echo export BUILD64=\"$BUILD64\" >> $CLFS/root/.profile
	    echo export CLFS_TARGET32=\"$CLFS_TARGET32\" >> $CLFS/root/.profile

            # generate fstab
            #
            # FIXME: CLFS 3.0.0-systemd fstab is excluding some of the standard
            #        virtual filesystems... /proc, /sys, /run, and /dev... not
            #        sure why.
            echo "# -*- mode: sh -*- " > $CLFS/etc/fstab
            if [ "$STAGE2_XEN" = "yes" ]; then
                echo "/dev/xvda1 / $CLFS_FSTYPE defaults 1 1" >> $CLFS/etc/fstab
            else
                echo "$CLFS_DEV / $CLFS_FSTYPE defaults 1 1" >> $CLFS/etc/fstab
            fi
            # NOTE: If configured, RUCKUS_DEV is passed in as the 2nd disk and
            #       mounted in /tmp/ruckus_dev.  /tmp/ruckus_dev/RUCKUS_PATH is
            #       then bind mounted to /ruckus.
            #
            # FIXME: Is there a performace penalty that could be avoided by
            #        mounting directly on /ruckus if RUCKUS_PATH == / ?
            #
            # NOTE: This is mounted read-only so that we can:
            #
            #       1) Continue to modify the /ruckus source tree from the
            #          dom0.
            #
            #       2) Make ABSOLUTELY sure that I don't ever smoke my /ruckus
            #          filesystem again.  Xen WILL let you pass /ruckus through
            #          read-write even if it's still mounted read-write on the
            #          dom0... at which point baaaad things happen.  :-/
            #
            #       3) Have the option to pass it through to multiple
            #          ruckus-builder domUs in parallel.
            #
            # FIXME: We have to set 'noload' for EXT4 to ensure that the
            #        journal doesn't get written to.  What happens if we're not
            #        using EXT4...?
            #
            if [ -n "$RUCKUS_DEV" ]; then
                mkdir -p $CLFS/ruckus $CLFS/tmp/ruckus_dev
                if [ "$STAGE2_XEN" = "yes" ]; then
                    echo "/dev/xvdb1 /tmp/ruckus_dev $RUCKUS_FSTYPE defaults,ro,noload 1 2" >> $CLFS/etc/fstab
                else
                    echo "$RUCKUS_DEV /tmp/ruckus_dev $RUCKUS_FSTYPE defaults 1 2" >> $CLFS/etc/fstab
                fi
                echo "/tmp/ruckus_dev /ruckus none bind 0 0" >> $CLFS/etc/fstab
            fi
            cat $ruckus_confdir/fstab >> $CLFS/etc/fstab || exit 1

            # install our inittab, which optionally starts the stage2 builder
            cp -v $ruckus_confdir/inittab $CLFS/etc/ || exit 1

	    # touch the stage2 file, which causes init to run the stage2 script
	    # on tty1 at boot
            if [ "$STAGE2_AUTO" = "yes" ]; then
	        touch $CLFS$RUCKUS_BOOTSTRAP_STAGE2_FILE || exit 1
            fi

	    ;;

	kernel)
            # FIXME: I should redo the kernel configs, perhaps using ruckusrd
            #        for initramfs...
            #
            #        Don't forget, this is the cross-compiled bare-bones kernel
            #        just to get us booted up...  if we can live w/out modules,
            #        that would be great.  That being said, it would be nice to
            #        be kinda distro-kernel-ish so that most people with most
            #        hardware can just use our bootstrap config... we'll see.
            #
            # FIXME: We should check out the specific version CLFS tests glibc
            #        with here, install it's headers in the final system
            #        ($CLFS/usr/include), and have the glibc package script
            #        slurp up the headers.

	    setup_generic $1 || exit 1

	    if [ -n "$BUILD64" ]; then
		kernel_config=kernel-config-64bit
	    else
		kernel_config=kernel-config-32bit
	    fi

	    # get ready
	    MAKE="make KBUILD_SRC=$source -f $source/Makefile"
	    MAKE+=" ARCH=$CLFS_ARCH CROSS_COMPILE=$CLFS_TARGET-"
	    pushd $builddir &&
	    $MAKE mrproper &&
	    popd || exit 1

	    # get set
	    cp -v $ruckus_confdir/$kernel_config $builddir/.config &&
	    pushd $builddir &&
	    $MAKE oldconfig &&
	    popd || exit 1

	    # NOTE: if you want to do a make menuconfig to tweak .config,
	    #       NCURSES_PREFIX has to be set to $PREFIX_TOOLS.

	    # go!
            #
            # FIXME: used to use INSTALL_MOD_PATH=$CLFS, but somewhere along
            #        the line CLFS switched to /tools... will modprobe work?
            #        will firmware get found?
	    pushd $builddir &&
	    $MAKE -j$JOBCOUNT_KBUILD &&
            $MAKE INSTALL_MOD_PATH=$PREFIX_TOOLS modules_install &&
	    popd || exit 1

            # FIXME: CLFS does a make firmware_install... but that doesn't seem
            #        to be needed.  modules_install is installing the firmware
            #        already.  I'm guessing this is because they don't want to
            #        assume that you've configured with module support... but
            #        you may still need firmware?
            #
            #$MAKE INSTALL_MOD_PATH=$PREFIX_TOOLS firmware_install

            # FIXME: Do we need to run depmod -b $CLFS?  Looks like
            #        modules_install does it at the end...

            # FIXME: Let's try and use the same kernel config, but just sed
            #        LOCALVERSION into it.  Then, after we've booted (and
            #        automagically loaded needed modules), remove
            #        lib/{modules,firmware}

            # FIXME: chowning everything to root is following the build and
            #        source symlinks into my source tree... obviously don't
            #        want that... but where should these symlinks really point
            #        to on the booted system?
            #
            # FIXME: get this path right... see comment above about /lib vs
            #        /tools/lib.
            rm -f $PREFIX_TOOLS/lib/modules/*/{build,source} || exit 1

	    # now actually install the resulting kernel files
	    pushd $builddir &&
            mkdir -p $CLFS/boot &&
	    cp -v arch/$CLFS_ARCH/boot/bzImage \
                $CLFS/boot/vmlinuz-ruckus-bootstrap &&
	    cp -v System.map $CLFS/boot/System.map-ruckus-bootstrap &&
	    cp -v .config $CLFS/boot/config-ruckus-bootstrap &&
	    popd || exit 1
	    ;;

        xen)
	    # NOTE: Just build the hypervisor.  This step is generally just
	    #       done to augment the bootstrap-early xen build on 32bit
	    #       systems with a cross-compiled 64bit hypervisor.
	    #
            # NOTE: Xen can't build out-of-tree, because of it's strange
            #       half-breed autotools build system.
	    build_in_tree=1 setup_generic $1 || exit 1

            # NOTE: It also needs to be explicitly configured (i.e., Makefile
            #       already exists).
            #
            # NOTE: We disable building tools, kernels, docs, and stubdom for
            #       stage1.
	    autoreconf=yes \
	        configure_generic $1 --prefix=$PREFIX_HOSTPREP \
		--disable-tools \
		--disable-kernels --disable-docs --disable-stubdom || exit 1

	    # NOTE: The dist target should just be building the hypervisor, as
	    #       per our configure args above.
	    #
	    # NOTE: We set DESTDIR to install into $PREFIX_HOSTPREP/boot.
	    MAKE="make"
            case "$CLFS_ARCH" in
                i386)
                    MAKE+=" XEN_TARGET_ARCH=x86_32"
                    ;;
                *)
                    MAKE+=" XEN_TARGET_ARCH=$CLFS_ARCH"
            esac
	    MAKE+=" CROSS_COMPILE=$CLFS_TARGET-"
	    pushd $builddir &&
	    $MAKE -j$JOBCOUNT dist &&
            $MAKE DESTDIR=$PREFIX_HOSTPREP install &&
	    popd || exit 1

            # also install in PREFIX_TOOLS if needed
            #
            # NOTE: If we're building a 32bit system, we won't be able to
            #       compile the hypervisor during the final build phase.
            #       Instead of building a new cross-compilation toolchain
            #       later, we just pre-install the hypervisor on the final
            #       system here.
            #
            # FIXME: Don't forget to make the xen final system build script
            #        slurp up the pre-existing hypervisor into it's package
            #        contents...
            if [ -z "$BUILD64" ]; then
                pushd $builddir &&
                $MAKE DESTDIR=$PREFIX_TOOLS install &&
	        popd || exit 1
            fi
	    ;;

	rsync)
	    # seems to have a parallel build problem... (still true as of
	    # v3.0.9)
	    JOBCOUNT=1 build_generic $1 $OPTS || exit 1
	    ;;

	*)
	    build_generic $1 $OPTS || exit 1
	    ;;
    esac
}


packages=""
packages+=" gmp"
packages+=" mpfr"
packages+=" mpc"
packages+=" isl"
packages+=" cloog"
packages+=" zlib"
packages+=" binutils"
packages+=" gcc"
packages+=" ncurses"

# busybox of doom!
#
# NOTE: We replace a ton of CLFS /tools packages by using busybox here.  The
#       busybox applets are less featureful than the full GNU tools, but
#       they're good enough to get our bootstrap system up and running quickly.
#
# NOTE: This means we'll be using busybox's init and mdev instead of sysvinit
#       and udev.  And we'll be providing our own simple bootscripts instead of
#       using the CLFS ones.
#
# NOTE: I'll keep the commented out list of CLFS packages up-to-date and in
#       order just to make pulling in CLFS updates easier.
#
# FIXME: what about my old patch for detecting non-/usr ncurses...?
#
# NOTE: I'll document some of the applet limitations here:
#
#       - findutils: No locate equivelent, but that's fine.
#
#       - mdev: Obviously, udev scripts won't work.
#
#       - init: Single runlevel only, but that's fine for now.
#
#       - losetup: No crypto support.
#
#       - bash/ash: Might run into bash script incompatibilities, although it
#         seems to be working fine for now.
#
#       - xz: Only supports decompressing... If we need to compress with xz
#         from the bootstrap system, we'll need to install the real xz package.
#         However, this does mean we're perfectly capable of untarring tar.xz
#         files transparently using busybox.
#
#         FIXME: is that still true?
#
#       - vi: Just as painful to use as I remember the original vi
#         being... shocking, and yet oddly refreshing, after years of being
#         spoiled by vim.
#
packages+=" busybox"

# bb
#
#packages+=" bash"
#packages+=" bzip2"

# NOTE: We skip check because it's unneeded at this point (do to our other
#       deviations from the CLFS book?)
#
#packages+=" check"

# bb
#
#packages+=" coreutils"
#packages+=" diffutils"

# FIXME: no longer in equivelent CLFS chapter?
#packages+=" bison"

packages+=" file"

# FIXME: no longer in equivelent CLFS chapter?
#packages+=" flex"

# bb
#
#packages+=" findutils"
#packages+=" gawk"

packages+=" gettext"

# bb
#
#packages+=" grep"
#packages+=" gzip"

# FIXME: no longer in equivelent CLFS chapter?
#packages+=" m4"

packages+=" make"

# bb
#
#packages+=" patch"
#packages+=" sed"
#packages+=" tar"

packages+=" texinfo"

# bb
#
#packages+=" util-linux"
#packages+=" vim"
#packages+=" xz-utils"


# boot prep
#
# FIXME: hmm... not sure how i'm gonna do this...  CLFS builds a bunch of
#        basic utils, udev, and a stripped down kernel in the target
#        filesystem (ie, not /tools) to make a bootable system.  Then
#        the next chapter in CLFS overwrites the installed files with the
#        final versions.  I guess this is doable...  The final system
#        packages are going to be packaged and installed with SRP, so we'll
#        have backup files all over the place that need to be remove.
#        Additionally, it would be nice if we could guarantee that there are
#        no bootstrap files left over.  Not sure how important that is,
#        though.

# NOTE: We skip check because it's unneeded at this point (do to our other
#       deviations from the CLFS book?)
#
#packages+=" bc"

# bb
#
#packages+=" boot-scripts"
#packages+=" e2fspogs"
#packages+=" kmod"
#packages+=" shadow"
#packages+=" sysvinit"
#packages+=" eudev"

packages+=" kernel"

# NOTE: We leave out grub for two reasons.
#
#       1) We boot our bootstrap system up as a Xen virtual machine, so we
#          don't need a bootloader.
#
#       2) I'd use SYSLINUX if we really need a bootloader at this point.
#          Better bang for the buck (EXT, FAT, IS9660 support, etc).
#
#packages+=" grub"

packages+=" create-dirs"

# NOTE: create-symlinks requires .build/busybox/busybox.links...
packages+=" create-symlinks"

# this will handle config files for init, mdev, users/groups, logfiles,
# login scripts, fstab, needed device nodes, etc
packages+=" create-conf"

# and so ends the list of CLFS packages


# We add this so that we can build perl in stage2, in-tree, from a git
# submodule (setup_generic uses rsync to copy the source tree in this case).
# Unfortunately, rsync needs to have perl in order to compile.  CLFS explicitly
# waits until booted to natively compile the temporary perl installation simply
# because it's such a pain to cross-compile, so we follow suit.  In other
# words, we're going to cross-compile rsync so that we don't have to
# cross-compile perl.
#
# NOTE: This also ensures that the rsync submodule is bootstrapped prior to
#       booting into the stage2 builder.
packages+=" rsync"


# If we have STAGE1_XEN_ONLY set, replace the entire pacakges list with just
# xen.  Otherwise, if we're building for 64bit, but building on 32bit, and
# want to use Xen for stage2, we need to cross-compile the hypervisor here in
# addition to the other packages.
if [ "$STAGE1_XEN_ONLY" = "yes" ]; then
    packages=xen
elif [ "$XEN_ENABLED" = "yes" ]; then
    packages+=" xen"
fi


mkdir -p $CLFS$PREFIX_TOOLS

# now iterate through building for our target architecture using our
# cross-compiler.
for p in $packages; do
    echo -e "\n+++++ building bootstrap-stage1 package: $p"
    build $p || exit 1
done


# make a backup of our progress, because starting over sucks
#
# NOTE: I considered removing the compression from our backup, because it
#       seemed like it was taking forever.  Here's some timing info from a
#       while ago.
#
#       Using tar's xz compression (-J), it's adding about 10 minutes to the
#       build time and compressed 890M down to about 180M on a 64bit-multilib
#       build.
#
#       Using bzip (-j) only took 2.5 minutes and resulted in a 290M archive.
#
#       Using gzip (-z) only took 1.5 minutes and resulted in a 350M file.
#
#       Piping tar into xz -0 took 1.5 minutes and resulted in a 240M file.
#       Looks like we have a winner.
#
if [ "$STAGE1_XEN_ONLY" != "yes" ]; then
    echo -n "creating bootstrap-stage1 backup... "
    mkdir -p $BUILDROOT &&
    tar -c \
        --exclude ./ruckus --exclude ./lost+found \
        --exclude ./ruckus-build \
        -C $CLFS . \
        | xz -0 > $BUILDROOT/baby-bootstrap-stage1.tar.xz || exit 1
    echo "done."
fi

exit 0
